dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: foxtel-platform-communication-whispir-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.1
- name: foxtel-platform-general-account-management-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.2
- name: foxtel-platform-general-netflix-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 0.0.0-PR-11-4-SNAPSHOT
